from gettext import gettext as _

icon_loc = "@icon_location@/share/icons/hicolor/scalable/mousam_icons/"

icons = {
    "0": icon_loc + "clear-day.svg",
    "1": icon_loc + "overcast-day.svg",
    "2": icon_loc + "overcast-day.svg",
    "3": icon_loc + "overcast.svg",
    "51": icon_loc + "partly-cloudy-day-drizzle.svg",
    "53": icon_loc + "drizzle.svg",
    "55": icon_loc + "overcast-drizzle.svg",
    "56": icon_loc + "partly-cloudy-day-snow.svg",
    "57": icon_loc + "overcast-snow.svg",
    "61": icon_loc + "partly-cloudy-day-rain.svg",
    "63": icon_loc + "rain.svg",
    "65": icon_loc + "thunderstorms-rain.svg",
    "66": icon_loc + "overcast-snow.svg",
    "67": icon_loc + "thunderstorms-rain.svg",
    "45": icon_loc + "fog.svg",
    "48": icon_loc + "fog.svg",
    "71": icon_loc + "partly-cloudy-day-snow.svg",
    "73": icon_loc + "snow.svg",
    "75": icon_loc + "snowflake.svg",
    "77": icon_loc + "snowflake.svg",
    "80": icon_loc + "overcast-day-rain.svg",
    "81": icon_loc + "rain.svg",
    "82": icon_loc + "thunderstorms-rain.svg",
    "85": icon_loc + "snow.svg",
    "86": icon_loc + "snowflake.svg",
    "95": icon_loc + "thunderstorms-rain.svg",
    "96": icon_loc + "thunderstorms-day-overcast-snow.svg",
    "99": icon_loc + "snowflake.svg",
    
    "0n": icon_loc + "clear-night.svg",
    "1n": icon_loc + "overcast-night.svg",
    "2n": icon_loc + "overcast-night.svg",
    "3n": icon_loc + "overcast.svg",
    "51n": icon_loc + "partly-cloudy-night-drizzle.svg",
    "53n": icon_loc + "drizzle.svg",
    "55n": icon_loc + "overcast-drizzle.svg",
    "56n": icon_loc + "partly-cloudy-night-snow.svg",
    "57n": icon_loc + "overcast-snow.svg",
    "61n": icon_loc + "partly-cloudy-night-rain.svg",
    "63n": icon_loc + "rain.svg",
    "65n": icon_loc + "thunderstorms-rain.svg",
    "66n": icon_loc + "overcast-snow.svg",
    "67n": icon_loc + "thunderstorms-rain.svg",
    "45n": icon_loc + "fog.svg",
    "48n": icon_loc + "fog.svg",
    "71n": icon_loc + "partly-cloudy-night-snow.svg",
    "73n": icon_loc + "snow.svg",
    "75n": icon_loc + "snowflake.svg",
    "77n": icon_loc + "snowflake.svg",
    "80n": icon_loc + "overcast-night-rain.svg",
    "81n": icon_loc + "rain.svg",
    "82n": icon_loc + "thunderstorms-rain.svg",
    "85n": icon_loc + "snow.svg",
    "86n": icon_loc + "snowflake.svg",
    "95n": icon_loc + "thunderstorms-rain.svg",
    "96n": icon_loc + "thunderstorms-night-overcast-snow.svg",
    "99n": icon_loc + "snowflake.svg",
    "arrow": icon_loc + "arrow.svg",
    "raindrop": icon_loc + "raindrop.svg",
    "raindrops": icon_loc + "raindrops.svg",
    "wind": icon_loc + "wind.svg",
}

bg_css = {
    "0": "bg-weather-clear-sky",
    "1": "bg-weather-few-clouds",
    "2": "bg-weather-few-clouds",
    "3": "bg-weather-overcast",
    "51": "bg-weather-showers-scattered",
    "53": "bg-weather-showers-scattered",
    "55": "bg-weather-showers-scattered",
    "56": "bg-weather-snow",
    "57": "bg-weather-snow",
    "61": "bg-weather-showers-scattered",
    "63": "bg-weather-showers-large",
    "65": "bg-weather-showers-large",
    "66": "bg-weather-snow",
    "67": "bg-weather-showers-large",
    "45": "bg-weather-fog",
    "48": "bg-weather-fog",
    "71": "bg-weather-snow",
    "73": "bg-weather-snow",
    "75": "bg-weather-snow",
    "77": "bg-weather-snow",
    "80": "bg-weather-showers-large",
    "81": "bg-weather-showers-large",
    "82": "bg-weather-showers-large",
    "85": "bg-weather-snow",
    "86": "bg-weather-snow",
    "95": "bg-weather-storm",
    "96": "bg-weather-storm",
    "99": "bg-weather-snow",

    "0n": "bg-weather-clear-sky-night",
    "1n": "bg-weather-few-clouds-night",
    "2n": "bg-weather-few-clouds-night",
    "3n": "bg-weather-overcast-night",
    "51n": "bg-weather-showers-scattered-night",
    "53n": "bg-weather-showers-scattered-night",
    "55n": "bg-weather-showers-scattered-night",
    "56n": "bg-weather-snow-night",
    "57n": "bg-weather-snow-night",
    "61n": "bg-weather-showers-scattered-night",
    "63n": "bg-weather-showers-large-night",
    "65n": "bg-weather-showers-large-night",
    "66n": "bg-weather-snow-night",
    "67n": "bg-weather-showers-large-night",
    "45n": "bg-weather-fog-night",
    "48n": "bg-weather-fog-night",
    "71n": "bg-weather-snow-night",
    "73n": "bg-weather-snow-night",
    "75n": "bg-weather-snow-night",
    "77n": "bg-weather-snow-night",
    "80n": "bg-weather-showers-large-night",
    "81n": "bg-weather-showers-large-night",
    "82n": "bg-weather-showers-large-night",
    "85n": "bg-weather-snow-night",
    "86n": "bg-weather-snow-night",
    "95n": "bg-weather-storm-night",
    "96n": "bg-weather-storm-night",
    "99n": "bg-weather-snow-night",
}
# 1 ->   indicates day
# 1n ->  indicates night

condition = {
    "0": _("Clear sky"),
    "1": _("Few Clouds"),
    "2": _("Partly Cloudy"),
    "3": _("Overcast"),
    "45": _("Fog"),
    "48": _("Mist"),
    "51": _("Light Drizzle"),
    "53": _("Moderate Drizzle"),
    "55": _("Heavy Intensity Drizzle"),
    "56": _("Light Freezing Drizzle"),
    "57": _("Heavy Freezing Drizzle"),
    "61": _("Light Rain"),
    "63": _("Moderate Rain"),
    "65": _("Heavy Rain"),
    "66": _("Light Freezing Rain"),
    "67": _("Heavy Freezing Rain"),
    "71": _("Light Snow Fall"),
    "73": _("Moderate Snow Fall"),
    "75": _("Heavy Snow Fall"),
    "77": _("Snow grains"),
    "80": _("Light Rain Showers"),
    "81": _("Moderate Rain Showers"),
    "82": _("Heavy Rain Showers"),
    "85": _("Light Snow Showers"),
    "86": _("Heavy Snow Showers "),
    "95": _("Thunderstorm"),
    "96": _("Thunderstorm with Hail"),
}

hpa_to_inhg = 0.02953
